### ISSUE TITLE
Malformed DESCRIPTION file

### ISSUE THREAD

**Issue by ellisvalentiner** [javadch/rquis#1]
Build check shows the DESCRIPTION file needs updating

```
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
Non-standard license specification:
  What license is it under?
```

https://www.r-project.org/Licenses/

**Comment by javadch** [comment]
The license file and type are defined in the LICENSE file in the repo. it is LGPL V 3.x.
@ellisvalentiner would you please add enough information from the LICENSE file to the package's description file

**Comment by ClaytonJY** [comment]
@ellisvalentiner, I hope you don't mind if I take this; the `DESCRIPTION` file needs a lot of attention and it seems like that should be done before worrying about much else.

**Comment by ClaytonJY** [comment]
Satisfied by PR #6 .
