### ISSUE TITLE
Sort out issues with config/ directory

### ISSUE THREAD

**Issue by ClaytonJY** [javadch/rquis#11]
Per @javadch, this folder needs to be placed in `RQt.Rcheck/` after running `R CMD check` the first time in order to pass the checking process.

Javad, do you mean `config/` needs to be in `RQt.RCheck/RQt/`? If so I can solve this by moving `config/` into `inst/` so it moved up during the build process. If it really needs to be at the _same level_ as `RQt.RCheck/RQt/`, rather than inside it, we have a bigger problem; that simply can't be done.

What's really going on with this folder? All I see are `*.jar` and `*.xml` files; perhaps the former could go in `insta/java` and the latter in `extdata`? If that works, I imagine there's lot's of references to update.

**Comment by javadch** [comment]
I am trying to put the config folder into the extdata, but it is not copied to the RQt.RCheck\RQt folder. I guess it is not a recursive file/folder copy and grabs only the files only from the first level beneath the extdata!
If it is possible to copy an arbitrary folder then and transfer it to RQt.RCheck\RQt\ Also if the functions have information about the running mode (Check/ normal use for example) I should be able to apply some changes to have R specific config location awareness...

**Comment by javadch** [comment]
I contacted @hadley, and still continuing, about the config issue. He suggested to put the config folder directly in the inst/ so that it appears in the root of the package. I did it, it works on build but still not in check.

**Comment by ClaytonJY** [comment]
@javadch it looks like things are moved from `inst/` _before_ `.Rbuildignore` is applied; if you remove the line `config` from `.Rbuildignore`, you should see `RQt.Rcheck/RQt/config/` after running `R CMD check`.

I would commit those changes but I'm still not sure that's the right thing to do with `config`; I suggest starting your own branch to play around with this.

**Comment by javadch** [comment]
From the conversation with Hadley it seems no problem, we have no other solution so far and the package is stuck; so I would suggest to stay with a solution/ work around that fixes the issue and upgrade to a better way when possible.
I'll create a branch for the config issue

**Comment by javadch** [comment]
Do you know of any way to determine whether a function is called during the check process.
so that I can say for example:
if(env== 'check')
     build_path_to_config(path1)
else
     build_path_to_config(path2)

**Comment by ClaytonJY** [comment]
That shouldn't matter, because `R CMD check` _builds_ the package very early in the checking:

```
* building ‘RQt_0.1.0.tar.gz’

'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  check '/tmp/Rtmp8fsTRO/RQt_0.1.0.tar.gz' --timings --no-multiarch 

```

The problem may be in using relative paths; this is why I used `system.file` in `weatherR.R` when fixing #10; that ensures correct finding of the external data file I moved to `extdata`.

I'm not sure where the documentation examples get ran from (stuff in `Examples/` is not run at all; see #18), but I think in many cases the examples don't need to be ran, so we could remove the example that isn't wrapped by `\dontrun{}` . It doesn't make sense to have an example both ran and not ran; see #19.

**Comment by ClaytonJY** [comment]
In reading up on demos, I came across the idea to use `tools`, see [here](http://r-pkgs.had.co.nz/misc.html). We should find a package that uses that directory, could give some clues.

**Comment by ClaytonJY** [comment]
What's the success condition for this bug? If it's "the config folder is in the root package directory after the package is built", I can pass it, but if it's "`No R CMD Check` errors on multiple platforms", I cannot. See my comment on #15.

**Comment by javadch** [comment]
it's "the config folder is in the root package directory after the package is built".
I enhanced the places  XQt searches for the config folder, so that it works both in check and when installed.
nothing about multi platform.
