### ISSUE TITLE
Fix LaTeX issue in documentation

### ISSUE THREAD

**Issue by ClaytonJY** [javadch/rquis#12]
Running `R CMD check` gives the following:

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... OK
* DONE
```

This means there's some improper documentation code, almost certainly in `R/RQt.R`, as that's where all the documentation is. This needs to be tracked down, and will resolve the last Warning I see.

**Comment by ClaytonJY** [comment]
Looked in the logs, this is related to #14 :

```
Overfull \hbox (479.5799pt too wide) in paragraph at lines 67--67
 []\T1/pcr/m/n/9 addedScript <- rqt.addScript(engine1, "CONNECTION cnn1 ADAPTER
=CSV SOURCE_URI=\TS1/pcr/m/n/9 '\T1/pcr/m/n/9 extdata\\\\\TS1/pcr/m/n/9 ' \T1/p
cr/m/n/9 PARAMETERS=delimiter:comma, fileExtension:csv, firstRowIsHeader:true")
[] 

Overfull \hbox (479.5799pt too wide) in paragraph at lines 71--71
 []\T1/pcr/m/n/9 addedScript <- rqt.addScript(engine1, "CONNECTION cnn1 ADAPTER
=CSV SOURCE_URI=\TS1/pcr/m/n/9 '\T1/pcr/m/n/9 extdata\\\\\TS1/pcr/m/n/9 ' \T1/p
cr/m/n/9 PARAMETERS=delimiter:comma, fileExtension:csv, firstRowIsHeader:true")
[] 
```

**Comment by ClaytonJY** [comment]
With @javadch's fixed I'm left with a new error about not having `Rd2.aux`; googling around shows lots of people with similar issues, but it sound's like it doesn't happen on Javad's machine so I'll just close this.

**Comment by javadch** [comment]
I get this message:
pdflatex not found! Not building PDF manual or vignettes.

**Comment by ClaytonJY** [comment]
I think that means you either don't have a LaTeX environment installed, or it's misconfigured. I think the gold standard on Windows is http://miktex.org/, have you installed that already?

**Comment by ClaytonJY** [comment]
Reopening for now; if you get pdflatex working, I'm curious if you get the same warning I do or not.

**Comment by javadch** [comment]
I had mixtex for a whilem but seems there is a problem after the few weeks ago's update. I'll do a clean install.

**Comment by ClaytonJY** [comment]
Your changes to `R/Rqt.R` didn't seem to fix all the overfull hboxes. Give me a bit and I'll submit a PR.
