### ISSUE TITLE
Shorten some lines in examples for rqt.addScript

### ISSUE THREAD

**Issue by ClaytonJY** [javadch/rquis#14]
There's a NOTE thrown by `R CMD check`:

```
* checking Rd line widths ... NOTE
Rd file 'rqt.addScript.Rd':
  \examples lines wider than 100 characters:
     addedScript <- rqt.addScript(engine1, "CONNECTION cnn1 ADAPTER=CSV SOURCE_URI='extdata\\\\' PARAMETERS=delimiter:comma, fileExtension:c ... [TRUNCATED]
     addedScript <- rqt.addScript(engine1, "CONNECTION cnn1 ADAPTER=CSV SOURCE_URI='extdata\\\\' PARAMETERS=delimiter:comma, fileExtension:c ... [TRUNCATED]

These lines will be truncated in the PDF manual.
```

These should be pretty easy to shorten up.

**Comment by ClaytonJY** [comment]
The quoted `XQt` scripts are over 100 characters by themselves. 

@javadch, will newlines in that string be properly escaped? If so, I could write the command on multiple lines before passing in to `rqt.addScript`, which will put `\n` characters in the string, e.g.

```
> script <- "foo
+ bar"
> script
[1] "foo\nbar"
```

**Comment by javadch** [comment]
In the xqt script files multiple line statements are supported. I guess the
line break is \r\n there. Test \n from inside R and let me know if does not
work.
I am currently busy with the jdk and config issues.

**Comment by javadch** [comment]
it adds a plus sign too!?
```
> script <- "foo
+ + bar"
> script
[1] "foo\n+ bar"
```

**Comment by javadch** [comment]
Did it as @ClaytonJY suggested.
