### ISSUE TITLE
Fix missing data in ex1.xqt

### ISSUE THREAD

**Issue by ClaytonJY** [javadch/rquis#17]
There's a line in `Examples/processes/ex1` which references `SOURCE_URI="D:\\Projects\\PhD\\Data\\`, a path that anyone but @javadch likely doesn't have. It uses the `data_10M` file in the directory, which is not currently in the package (not even in `extdata`).

@javadch I think you brought this file up in either email or some other issue and asked if we should remove it or not because it's a big file, not realizing it's not in there. In the interest of time I recommend we either remove ex1.xqt entirely, or have it use a smaller file. What do you think?

**Comment by javadch** [comment]
I vote for removing it. Later when the package is more mature we can think
of having a smaller dataset and adding the example again

**Comment by ClaytonJY** [comment]
Okay great, I can start on this and #18 tonight or tomorrow.
