### ISSUE TITLE
Non-standard files/directories found at top level

### ISSUE THREAD

**Issue by ellisvalentiner** [javadch/rquis#2]
```
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
Non-standard files/directories found at top level:
  ‘Examples’ ‘config’ ‘docs’
```

**Comment by javadch** [comment]
Examples and docs can go somewhere else if there is a standard location for them, provided that we edit the examples in the documentation and sample scripts. But, config folder can not be moved.
Maybe @ClaytonJY can find a solution.

**Comment by ClaytonJY** [comment]
Can the folders `Examples` and `docs` be excluded from the build process entirely? I can add them to `.Rbuildignore`, but solving the `config` issue is a bigger task. Will read up more on using `.jar` files in R packages, as that is new to me.

Eventually, Examples and docs should probably become vignettes (written in (R)markdown).

**Comment by javadch** [comment]
The Examples folder contains some test scripts mentioned in the documentation of the package functions. I guess there should be a standard way to add them to the project.
The docs folder can be ignored from the build, by the way.

**Comment by javadch** [comment]
The config file is not about Java, it is a folder that should be copied to the check folder and be recognized as a normal folder at build time. There should be a way to introduce it to the R build system

**Comment by ClaytonJY** [comment]
Satisfied by PR #6 , at least for now.
