### ISSUE TITLE
Do something with rqt.getPlot

### ISSUE THREAD

**Issue by ClaytonJY** [javadch/rquis#22]
The function `rqt.getPlot` is all commented out at the moment. @javadch, is it important to get this working in v0.1, or should it be removed?

**Comment by javadch** [comment]
It returns the XQt plots as jpeg files to R. Currently does not work and
can bw removed. But docuemnt it in an issue ao that it is not lost.

**Comment by ClaytonJY** [comment]
Have this fix on a branch `remove-getPlot`, which I will file a PR for once #24 is merged.

**Comment by javadch** [comment]
Removed on remove-getPlot branch.
