### ISSUE TITLE
Malformed NAMESPACE file

### ISSUE THREAD

**Issue by ellisvalentiner** [javadch/rquis#3]
```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘rJava’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```

**Comment by javadch** [comment]
These are my RStudio settings for the RQt project (Tools -> Project Options)
Build and Reload R CMD INSTALL additional options: --no-multiarch --with-keep.source
Check Package R CMD check additional options: --no-multiarch --no-clean
Build Binary Package R CMD INSTALL additional options: --no-multiarch

**Comment by javadch** [comment]
The rJava package, at least on my 64 bits machine, does not generate 32 bits version, so I set --no-multiarch.

**Comment by ClaytonJY** [comment]
@ellisvalentiner , did you load the RQt.Rproj file in RStudio before building? This picks up the settings Javad describes above, and I'm able to build successfully with those settings.

**Comment by ClaytonJY** [comment]
Took ownership as I'm filing a large PR to cleanup this and other small issues.

**Comment by ClaytonJY** [comment]
Satisfied by merging PR #6 .
