### ISSUE TITLE
Check Java configuration when loading package

### ISSUE THREAD

**Issue by ClaytonJY** [javadch/rquis#31]
Right now, the best way of checking that `JDK_HOME` was found/set and that the JDK is >= 1.8 is to run `demo("test", package="RQt")`. There's gotta be a good way to check configuration without discrete user action; perhaps in `.onLoad`?

**Comment by javadch** [comment]
I suggest to have a java check function in the API so that when called from the onLoad, informs the user about required steps if any thing is missing.

**Comment by ClaytonJY** [comment]
That sounds great; handle it all in Java land. Assigning to you for now.

**Comment by javadch** [comment]
working on it in the java-check branch (child of develop)
